### ISSUE TITLE
FxA-97: password blocklist

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#4] opened 2016-07-07 04:39 UTC
Engineering bug tree: https://waffle.io/mozilla/fxa?milestone=FxA-97:%20password%20blocklist

**Comment by rfk** [comment] 2016-08-04 22:07
The first version of this is shipping in train-66; still working on the "more info" link in train-67

**Comment by davismtl** [comment] 2016-08-18 22:27
Adding a need inspiration link which will open a modal.

**Comment by vladikoff** [comment] 2016-09-08 18:31
PR to close feature is here: https://github.com/mozilla/fxa/pull/187

**Comment by davismtl** [comment] 2016-09-08 22:05
Results logged here: 
https://github.com/mozilla/fxa/blob/1e01ca7d370dd5dd8bf37f3d88ac3aaa72630e25/features/FxA-97-password-strength/README.md

Problem is that we don't have a control. We measured 100% of the 10% of users we can measure therefor we don't know if the below drops are normal:

Registration success rate dropped by 10%. (New accounts / views of form)
Quality of passwords dropped by 2%.
2% of users clicked on "need inspiration" link.
0.84% of users that were displayed the message "need inspiration"  (1.67% saw this message) are dropping out of signup because they are not returning from from sumo. 

_How did registration rate drop 10% if so few people engaged with the feature?_

**Comment by davismtl** [comment] 2016-09-08 22:18
Take away is to investigate drop: https://waffle.io/mozilla/fxa/cards/57d1e344fde1012f0384b0ec

Assign to @ryanfeeley to read results and close.

**Comment by rfk** [comment] 2016-09-15 22:10
> How did registration rate drop 10% if so few people engaged with the feature?

We followed up on this here: https://github.com/mozilla/fxa-content-server/issues/4130

**Comment by davismtl** [comment] 2016-09-15 22:14
from mtg
- The 10% is due to the way we measure, not caused by this feature release.
- @ryanfeeley to propose new ideas for password hint.

We will kill the need inspiration link since not many people are clicking it and 40% of people are not coming back.

Closing this feature as of now.

**Comment by vbudhram** [comment] 2016-09-15 22:15
> Quality of passwords dropped by 2%.

This was added July 19, which would potentially correspond to the next train cycle. It reports password errors when all letters or numbers.

https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/password-strength-mixin.js#L89

**Closed as completed** 2016-09-15 22:16 UTC
