### ISSUE TITLE
dockerflow everywhere

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#67] opened 2017-02-09 05:44 UTC
This is step zero in our "deploy faster" plan for Q1.

Engineering bugs: https://waffle.io/mozilla/fxa?milestone=FxA-67:%20dockerflow%20everywhere

**Comment by davismtl** [comment] 2017-02-23 20:55
from mtg:
- sean started working on it

**Comment by davismtl** [comment] 2017-03-02 20:49
from mtg:
- on track to finish by end of quarter
- we plan on discussing this a lot in our work week beginning of april
- @rfk to add a link for all the issues related to these efforts

**Comment by rfk** [comment] 2017-03-03 06:17
@jbuck can you please confirm whether this set of bugs captures all the services that are yet to move to dockerflow?  https://waffle.io/mozilla/fxa?milestone=FxA-67:%20dockerflow%20everywhere

**Comment by jbuck** [comment] 2017-03-03 14:40
@rfk confirmed!

**Comment by davismtl** [comment] 2017-03-23 20:07
from mtg:
- @vladikoff says that some bugs left that need to be double checked
- will have a look at it on Monday and will also review it as a team during the work week

**Comment by davismtl** [comment] 2017-04-27 20:33
from mtg:
- according to rfk, shipping train 86 on top of docker but vlad is not sure ( @jbuck , can you confirm or deny?)
- dev environment is totally dockerized
- so far so good

CLOSE this card when we successfully ship to production using docker for the first time.

**Comment by jbuck** [comment] 2017-04-28 17:54
We'll try shipping some parts of train 86 with docker - fxa-auth will need to wait a bit because the customs server ships from a private repo and we don't have that ready yet

**Comment by rfk** [comment] 2017-05-04 20:35
* train-86 oauth-server and content-server are being deployed via dockerflow, so we'll see how that goes :-)

**Comment by rfk** [comment] 2017-05-11 20:17
According to [1] the oauth-server is now deployed via docker \o/

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1361605#c4

**Comment by davismtl** [comment] 2017-05-11 20:24
from mtg:
- content-server is next. We will follow up in 87 to see how we'll approach it.
- @jbuck what are your thoughts?

**Comment by jbuck** [comment] 2017-05-11 23:18
Slow and steady wins the race!

**Comment by davismtl** [comment] 2017-05-12 20:52
CLOSED. FEATURE CARD MOVED TO: 
https://projects.growthhackers.com/s2/LJiFj6lV-xzlgcO8S0dCAw

**Closed as completed** 2017-08-08 05:22 UTC
Labels: measuring
