### ISSUE TITLE
FxA-106: sign-in unblock

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#11] opened 2016-07-07 04:44 UTC
Final Feature Doc: 
https://github.com/mozilla/fxa/blob/a3fd628462d6f59dcc699bb84f1b8791994ac8b0/features/FxA-106-signin-unblock/README.md

Draft feature doc: https://docs.google.com/document/d/1qbzfA21T0HoHpgxXlpO26qcCQDx2v0PUbcoHW9XtxQQ/edit#

Prototype engineering bugs: https://waffle.io/mozilla/fxa?milestone=FxA-106:%20email%20captcha

**Comment by rfk** [comment] 2016-07-18 10:12
Based on feedback from @ryanfeeley and others, I'm trying out a Google Doc for initial draft of this feature description.  So here we go, my attempt at the "email recaptcha" feature:

  https://docs.google.com/document/d/1qbzfA21T0HoHpgxXlpO26qcCQDx2v0PUbcoHW9XtxQQ/edit#

In the process of writing this out, I came to re-name it to "sign-in authorization" since it's actually quite similar to the sign-in confirmation feature, but operating earlier in the flow.  The idea is to allow the user an escape hatch from our current errno=125 "Blocked for security reasons" response, which is currently a dead-end.

@davismtl @ryanfeeley @shane-tomlinson I'd love to get your thoughts on the initial idea here.

**Comment by vladikoff** [comment] 2016-08-11 22:17
from mtg:
- final screen in the works after the user has verified.
- feature doc is in the works

**Comment by rfk** [comment] 2016-08-22 05:23
On advice from @davismtl I'm re-naming this back to "email captcha" to avoid confusion with the existing "sign-in confirmation" feature.

**Comment by davismtl** [comment] 2016-09-15 22:32
from mtg:
@rfk to move over to github to finalize feature doc

We'll also see in the future if we can merge this with login confirmation if it performs better.

**Comment by rfk** [comment] 2016-09-23 02:42
Update: @shane-tomlinson volunteered to migrate the feature-doc into github, and I'm on the hook to review it.

**Comment by davismtl** [comment] 2016-09-29 21:51
from mtg:
@shane-tomlinson is feature doc migrated?

No code has landed yet. Front end code is still in progress. 
Prob still a train or two away from production.

**Comment by shane-tomlinson** [comment] 2016-09-30 04:53
> @shane-tomlinson is feature doc migrated?

Yerp - https://github.com/mozilla/fxa/pull/194. @rfk gave some feedback, need to update.

**Comment by davismtl** [comment] 2016-10-06 19:15
will likely land in 72

**Comment by davismtl** [comment] 2016-10-27 19:29
from mtg: 
- shipping this week in 72
- being rolled out at 50%. 
- @shane-tomlinson will we be able to measure this a/b test? (seems to be some doubts) If not, what are we measuring by doing a 50/50?

**Comment by rfk** [comment] 2016-11-09 04:07
@seanmonstar and I have been poking at a preliminary flow-metrics analysis of this feature, which you can find here:

  https://sql.telemetry.mozilla.org/queries/1626/source#2878

We've still had a few hiccups with ingesting the flow events into our pipeline, but from the data that's there we see some interesting things:
-  Of people who send an unblock email, around 80% of them successfully consume the code.  This is in line with other measures of the success rate of our email loops in general.
- Prior to launching this feature, around 5% of flows getting `customs.blocked` eventually succeeded all the way through to `account.signed`.  AFAWCT these are folks who were patient enough to wait for the their rate-limiting to expire.
- At 50% rollout, around 12% of flows getting `customs.blocked` succeed at getting through to `account signed`.  That's pretty good!  We could end up pushing 20% successful completion when we complete the rollout.
- Around 25% of flows getting `customs.blocked` requested an unblock email to be sent.  50% don't have that option at all, so what has happened to the other 25% of people who in theory _could_ have requested a code, but didn't?  It's my understanding that the content-server submits the unblock code request more-or-less automatically.

So, some things to dig into here, but I call the early results a win overall!

**Comment by shane-tomlinson** [comment] 2016-11-09 11:07
> Around 25% of flows getting customs.blocked requested an unblock email to be sent. 50% don't have that option at all, so what has happened to the other 25% of people who in theory could have requested a code, but didn't? It's my understanding that the content-server submits the unblock code request more-or-less automatically.

The content server requests the email to be sent IFF the auth server responds with a throttled or request_blocked response containing `verificationReason: 'login', verificationMethod: 'email-captcha'`. Last week while testing against prod, I was hard blocked for 15, then 30 minutes, with no way to unblock myself. I suspect in some cases the auth or customs server is not permitting unblocking when it probably should.

**Comment by davismtl** [comment] 2016-11-10 20:23
from mtg:
- feature at 50% should be increasing sign-in volume by 2%
- once rolled-out at 100% should increase volume by 4%

**Comment by rfk** [comment] 2016-11-17 19:55
We're at 100% rollout and feature appears to be working well, although fully 50% of blocked flows don't appear to be "hard-blocked" and unable to use this feature.  If we can figure out why, there's probably still some low-hanging fruit here in terms of sign-in success rate.

**Comment by davismtl** [comment] 2016-11-17 20:18
from mtg: 
- it is possible to be blocked but not be able to get unblocked however we are unsure why so many people are running into it. (50%)
- requires investigation
- some users have reported bugs or have been stuck in the flow. e.g. not getting email. Caused by Outlook?

**Comment by rfk** [comment] 2016-11-25 10:53
One theory for the hard-blocking happening here is users on shared IPs, as follows:

* There's a series of failed login attempts on a shared IP, causing that IP to get banned.
* I attempt to login from that IP.  The login is blocked because the IP is banned, and fxa-auth-server offers to let me use an unblock code
* I request an unblock code be sent.  But my IP is banned, so the attempt to send an email *also* gets blocked, and I'm stuck unable to block myself.

Resolving this would involve untangling the single "this IP is banned" flag that we currently have, into separate "this IP is banned from making more login attempts" and "this IP is banned from sending more emails" flags.  The propsed refactor in [1] was partly inspired by wanting to address this, although there's probably a simpler intermediate step.

[1] https://github.com/mozilla/fxa-customs-server/issues/128

**Comment by rfk** [comment] 2016-12-01 20:29
Remaining open questions:

* Does the capitalization fix in train-75 resolve the "invalid authentication code" issue?
* What should we do about the "hard-blocked" users?

**Comment by rfk** [comment] 2016-12-08 18:20
> What should we do about the "hard-blocked" users?

According to Kibana, about 15% of calls to `/send_unblock_code` are returning a rate-limited "429" response:

  https://kibana-fxa-us-west-2.prod.mozaws.net/index.html#dashboard/temp/AVjfqQpJTlXM2FwOZEAf

![screen shot 2016-12-08 at 08 17 24](https://cloud.githubusercontent.com/assets/34695/21021983/0d8e33b2-bd1f-11e6-9e03-ed96d0ad3f70.png)

I suspect the majority of these are folks on a shared IP, and we could get them unblocked if we decouple rate-limiting of logins by IP, and rate-limiting of account status checks by IP.  It's probably worth trying to do a simple experiment along those lines.

**Comment by rfk** [comment] 2016-12-15 20:16
@seanmonstar and @rfk can chat about how to unblock this last 15% of people by reconfiguring customs-server rules.

**Comment by davismtl** [comment] 2016-12-22 20:43
from mtg:
- moved to measuring
- https://sql.telemetry.mozilla.org/queries/1958/source#3478 (invalid logins going down)
- There are remaining unblocking codes that don't work which might be caused by typos
- We should capture user feedback here too to perhaps identify other causes
- We should see improved unblock funnel as a result but might be too early to tell: https://sql.telemetry.mozilla.org/queries/1626#2878
- We will let more data to come in
- We should probably look at UA to see if there are any differences

**Comment by davismtl** [comment] 2017-01-12 20:20
from mtg: 
- followed up with Rachel. Will be getting access to a new tool for review user input
- there was a down time in december with input data
- will update accordingly

**Comment by vladikoff** [comment] 2017-01-24 19:59
Need to check the latest error metrics....

**Comment by davismtl** [comment] 2017-01-26 20:18
from mtg:

- Invalid code chart: 
https://sql.telemetry.mozilla.org/queries/1958#3631
- We are going to move this to done.
- We need to discuss moving forward on increasing the limit of invalid password attempts
- Also need do a retrospective on unblock codes to see if it is behaving as we intended

**Closed as completed** 2017-01-26 20:18 UTC
